sudo: required
services:
  - docker

before_install:
  - docker build -t vvavepacket/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vvavepacket/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env1"
  bucket_name: "elasticbeanstalk-us-east-1-510158725010"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
